INSERT IGNORE INTO autores (autor) VALUES ('J.K. Rowling');
INSERT IGNORE INTO autores (autor) VALUES ('W. Frederick Zimmerman');
INSERT IGNORE INTO autores (autor) VALUES ('Douglas Adams');
INSERT IGNORE INTO autores (autor) VALUES ('Bill Bryson');
INSERT IGNORE INTO autores (autor) VALUES ('J.R.R. Tolkien');
INSERT IGNORE INTO autores (autor) VALUES ('Chris   Smith');
INSERT IGNORE INTO autores (autor) VALUES ('Jude Fisher');
INSERT IGNORE INTO autores (autor) VALUES ('Dave Thomas');
INSERT IGNORE INTO autores (autor) VALUES ('Mark   Watson');
INSERT IGNORE INTO autores (autor) VALUES ('Gary Paulsen');
INSERT IGNORE INTO autores (autor) VALUES ('Donna Ickes');
INSERT IGNORE INTO autores (autor) VALUES ('Molly Hatchet');
INSERT IGNORE INTO autores (autor) VALUES ('Dale Peck');
INSERT IGNORE INTO autores (autor) VALUES ('Bud Cheff Sr.');
INSERT IGNORE INTO autores (autor) VALUES ('Angela Knight');
INSERT IGNORE INTO autores (autor) VALUES ('Delia Sherman');
INSERT IGNORE INTO autores (autor) VALUES ('Patricia A. McKillip');
INSERT IGNORE INTO autores (autor) VALUES ('Zilpha Keatley Snyder');
INSERT IGNORE INTO autores (autor) VALUES ('Elaine Cunningham');
INSERT IGNORE INTO autores (autor) VALUES ('Philippa Carr');
INSERT IGNORE INTO autores (autor) VALUES ('Edward P. Jones');
INSERT IGNORE INTO autores (autor) VALUES ('Satyajit Das');
INSERT IGNORE INTO autores (autor) VALUES ('Mark Smylie');
INSERT IGNORE INTO autores (autor) VALUES ('John McPhee');
INSERT IGNORE INTO autores (autor) VALUES ('Wendy Wasserstein');
INSERT IGNORE INTO autores (autor) VALUES ('Heidi Hayes Jacobs');
INSERT IGNORE INTO autores (autor) VALUES ('Heidi Boyd');
INSERT IGNORE INTO autores (autor) VALUES ('Heidi Baker');
INSERT IGNORE INTO autores (autor) VALUES ('Johanna Spyri');
INSERT IGNORE INTO autores (autor) VALUES ('Heidi Betts');
INSERT IGNORE INTO autores (autor) VALUES ('Rolland Baker');
INSERT IGNORE INTO autores (autor) VALUES ('Heidi Murkoff');
INSERT IGNORE INTO autores (autor) VALUES ('Heidi Fleiss');
INSERT IGNORE INTO autores (autor) VALUES ('Heidi W. Boehringer');
INSERT IGNORE INTO autores (autor) VALUES ('Frank Herbert');
INSERT IGNORE INTO autores (autor) VALUES ('Brian Herbert');
INSERT IGNORE INTO autores (autor) VALUES ('James Van Hise');
INSERT IGNORE INTO autores (autor) VALUES ('Gary Russell');
INSERT IGNORE INTO autores (autor) VALUES ('Susan E. Tifft');
INSERT IGNORE INTO autores (autor) VALUES ('Bryce Courtenay');
INSERT IGNORE INTO autores (autor) VALUES ('Dennis Brindell Fradin');
INSERT IGNORE INTO autores (autor) VALUES ('Francis Frangipane');
INSERT IGNORE INTO autores (autor) VALUES ('John C. Maxwell');
INSERT IGNORE INTO autores (autor) VALUES ('Dave Lakhani');
INSERT IGNORE INTO autores (autor) VALUES ('Louis E. Catron');
INSERT IGNORE INTO autores (autor) VALUES ('Adam Ginsberg');
INSERT IGNORE INTO autores (autor) VALUES ('Marsha Collier');
INSERT IGNORE INTO autores (autor) VALUES ('Debra Schepp');
INSERT IGNORE INTO autores (autor) VALUES ('Chris Malta');
INSERT IGNORE INTO autores (autor) VALUES ('Julia Wilkinson');
INSERT IGNORE INTO autores (autor) VALUES ('Lucas Carlson');
INSERT IGNORE INTO autores (autor) VALUES ('Ruby Ann Boxcar');
INSERT IGNORE INTO autores (autor) VALUES ('Ruby Banks-Payne');
INSERT IGNORE INTO autores (autor) VALUES ('Rob Orsini');
INSERT IGNORE INTO autores (autor) VALUES ('Ruby Le Bois');
INSERT IGNORE INTO autores (autor) VALUES ('Leo Tolstoy');
INSERT IGNORE INTO autores (autor) VALUES ('Marianne Sturman');
INSERT IGNORE INTO autores (autor) VALUES ('Gloria Goldreich');
INSERT IGNORE INTO autores (autor) VALUES ('Anthony Thorlby');
INSERT IGNORE INTO autores (autor) VALUES ('Mulk Raj Anand');
INSERT IGNORE INTO autores (autor) VALUES ('John Banville');
INSERT IGNORE INTO autores (autor) VALUES ('Eliot Ness');
INSERT IGNORE INTO autores (autor) VALUES ('Narendra Jadhav');
INSERT IGNORE INTO autores (autor) VALUES ('V.T. Rajshekar');
INSERT IGNORE INTO autores (autor) VALUES ('Oliver Mendelsohn');
INSERT IGNORE INTO autores (autor) VALUES ('Vasant Moon');
INSERT IGNORE INTO autores (autor) VALUES ('Peter Achinstein');
INSERT IGNORE INTO autores (autor) VALUES ('Barry R. Cournoyer');
INSERT IGNORE INTO autores (autor) VALUES ('John Carratello');
INSERT IGNORE INTO autores (autor) VALUES ('George Smoot');
INSERT IGNORE INTO autores (autor) VALUES ('Madeleine L''Engle');
INSERT IGNORE INTO autores (autor) VALUES ('Tara MacCarthy');
INSERT IGNORE INTO autores (autor) VALUES ('Valerie Metcalf Estoye');
INSERT IGNORE INTO autores (autor) VALUES ('Charlotte S. Jaffe');
INSERT IGNORE INTO autores (autor) VALUES ('Anne Troy');
INSERT IGNORE INTO autores (autor) VALUES ('Cynthia Harrod-Eagles');
INSERT IGNORE INTO autores (autor) VALUES ('Charles Todd');
INSERT IGNORE INTO autores (autor) VALUES ('Christopher Waldrep');
INSERT IGNORE INTO autores (autor) VALUES ('Ewan McGregor');
INSERT IGNORE INTO autores (autor) VALUES ('Daniel Abraham');
INSERT IGNORE INTO autores (autor) VALUES ('Charles Willeford');
INSERT IGNORE INTO autores (autor) VALUES ('Kirby Olson');
INSERT IGNORE INTO autores (autor) VALUES ('Tom Wolfe');
INSERT IGNORE INTO autores (autor) VALUES ('Edward Lear');
INSERT IGNORE INTO autores (autor) VALUES ('Quentin Blake');
INSERT IGNORE INTO autores (autor) VALUES ('Henry Miller');
INSERT IGNORE INTO autores (autor) VALUES ('Matthew Carmona');
INSERT IGNORE INTO autores (autor) VALUES ('Erving Goffman');
INSERT IGNORE INTO autores (autor) VALUES ('Charles A. Coulombe');
INSERT IGNORE INTO autores (autor) VALUES ('Sian Phillips');
INSERT IGNORE INTO autores (autor) VALUES ('Calvin Morrill');
INSERT IGNORE INTO autores (autor) VALUES ('Mark C. Childs');
INSERT IGNORE INTO autores (autor) VALUES ('F. Belton Joyner Jr.');
INSERT IGNORE INTO autores (autor) VALUES ('Braiden Rex-Johnson');
INSERT IGNORE INTO autores (autor) VALUES ('Malcolm Miles');
INSERT IGNORE INTO autores (autor) VALUES ('Henry James');
INSERT IGNORE INTO autores (autor) VALUES ('Lyn Cowan');
INSERT IGNORE INTO autores (autor) VALUES ('Joel Porte');
INSERT IGNORE INTO autores (autor) VALUES ('Marguerite Duras');
INSERT IGNORE INTO autores (autor) VALUES ('John E. Upledger');
