INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Harry Potter and the Half-Blood Prince (Harry Potter, #6)', 1, 1, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Harry Potter and the Order of the Phoenix (Harry Potter, #5)', 1, 1, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Harry Potter and the Sorcerer''s Stone (Harry Potter, #1)', 1, 2, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Harry Potter and the Chamber of Secrets (Harry Potter, #2)', 1, 3, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)', 1, 1, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Harry Potter and the Goblet of Fire (Harry Potter, #4)', 1, 3, 2002);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Harry Potter Boxed Set, Books 1-5 (Harry Potter, #1-5)', 1, 3, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Unauthorized Harry Potter Book Seven News: "Half-Blood Prince" Analysis and Speculation', 2, 4, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Harry Potter Collection (Harry Potter, #1-6)', 1, 3, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Ultimate Hitchhiker''s Guide: Five Complete Novels and One Story (Hitchhiker''s Guide to the Galaxy, #1-5)', 3, 5, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Ultimate Hitchhiker''s Guide to the Galaxy (Hitchhiker''s Guide to the Galaxy, #1-5)', 3, 6, 2002);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Hitchhiker''s Guide to the Galaxy (Hitchhiker''s Guide to the Galaxy, #1)', 3, 7, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Ultimate Hitchhiker''s Guide (Hitchhiker''s Guide to the Galaxy, #1-5)', 3, 8, 1996);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('A Short History of Nearly Everything', 4, 9, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Bill Bryson''s African Diary', 4, 9, 2002);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Bryson''s Dictionary of Troublesome Words: A Writer''s Guide to Getting It Right', 4, 9, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('In a Sunburned Country', 4, 9, 2001);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('I''m a Stranger Here Myself: Notes on Returning to America After Twenty Years Away', 4, 9, 2000);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Lost Continent: Travels in Small Town America', 4, 10, 1990);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Neither Here nor There: Travels in Europe', 4, 10, 1993);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Notes from a Small Island', 4, 10, 1997);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Mother Tongue: English and How It Got That Way', 4, 10, 1991);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings', 5, 11, 2012);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Lord of the Rings (The Lord of the Rings, #1-3)', 5, 12, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Fellowship of the Ring (The Lord of the Rings, #1)', 5, 12, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Lord of the Rings: Weapons and Warfare', 6, 12, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Lord of the Rings: Complete Visual Companion', 7, 12, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Agile Web Development with Rails: A Pragmatic Guide', 8, 13, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Ruby Quickly: Ruby and Rails for the Real World', 9, 14, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Hatchet (Brian''s Saga, #1)', 10, 15, 2000);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Hatchet: A Guide for Using "Hatchet" in the Classroom', 11, 16, 1994);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Guts: The True Stories behind Hatchet and the Brian Books', 10, 17, 2001);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Molly Hatchet - 5 of the Best', 12, 18, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Hatchet Jobs: Writings on Contemporary Fiction', 13, 19, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Woodsman and His Hatchet: Eighty Years on Back Country Survival', 14, 20, 1996);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('A Changeling for All Seasons (Changeling Seasons #1)', 15, 21, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Changeling (Changeling, #1)', 16, 22, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Changeling Sea', 17, 23, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Changeling', 18, 24, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Shadows in the Starlight (Changeling Detective, #2)', 19, 25, 2007);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Changeling (Daughters of England, #15)', 20, 26, 1990);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Known World', 21, 27, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Traders, Guns & Money: Knowns and Unknowns in the Dazzling World of Derivatives', 22, 28, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Artesia: Adventures in the Known World', 23, 29, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The John McPhee Reader (John McPhee Reader, #1)', 24, 30, 1982);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Uncommon Carriers', 24, 31, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Heirs of General Practice', 24, 30, 1986);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Control of Nature', 24, 30, 1990);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Annals of the Former World', 24, 30, 1999);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Coming Into the Country', 24, 30, 1991);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('La Place de la Concorde Suisse', 24, 30, 1994);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Giving Good Weight', 24, 30, 1994);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Second John McPhee Reader (John McPhee Reader, #2)', 24, 30, 1996);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Rising from the Plains', 24, 30, 1987);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Heidi Chronicles', 25, 32, 2002);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Heidi Chronicles: Uncommon Women and Others & Isn''t It Romantic', 25, 33, 1991);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Active Literacy Across the Curriculum: Strategies for Reading, Writing, Speaking, and Listening', 26, 34, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Simply Beautiful Beaded Jewelry', 27, 35, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Always Enough: God''s Miraculous Provision Among the Poorest Children on Earth', 28, 36, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Mapping the Big Picture: Integrating Curriculum & Assessment K-12', 26, 37, 1997);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Heidi (Heidi, #1-2)', 29, 38, 2002);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Getting Results with Curriculum Mapping', 26, 39, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Cinnamon and Roses (Rose Trilogy, #1)', 30, 40, 2000);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('There''s Always Enough: The Miraculous Move of God in Mozambique', 31, 41, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('What to Expect the First Year (What to Expect)', 32, 42, 2003);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Player''s Handbook: The Ultimate Guide on Dating and Relationships', 33, 43, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Simply Beautiful Beading: 53 Quick and Easy Projects', 27, 35, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Chasing Jordan', 34, 44, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Seven-Year Seduction', 30, 45, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('God Emperor of Dune (Dune Chronicles, #4)', 35, 46, 1987);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Dune (Dune Chronicles, #1)', 35, 46, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Chapterhouse: Dune (Dune Chronicles #6)', 35, 46, 1987);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Dune Messiah (Dune Chronicles #2)', 35, 46, 1987);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Dreamer of Dune: The Biography of Frank Herbert', 36, 25, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Secrets of Frank Herbert''s Dune', 37, 47, 2000);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Heretics of Dune (Dune Chronicles, #5)', 35, 48, 1984);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Road to Dune', 35, 49, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Children of Dune (Dune Chronicles #3)', 35, 46, 1987);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Heretics of Dune (Dune Chronicles #5)', 35, 46, 1987);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Lord of the Rings: The Art of the Fellowship of the Ring', 38, 12, 2002);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Patriarch: The Rise and Fall of the Bingham Dynasty', 39, 50, 1993);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Power of One (The Power of One, #1)', 40, 11, 1996);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Power of One: Daisy Bates and the Little Rock Nine', 41, 51, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Power of One Christlike Life', 42, 52, 2000);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Power of One: One Person, One Rule, One Month', 43, 53, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Power of an Hour: Business and Life Mastery in One Hour a Week', 44, 54, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('The Power of One: The Solo Play for Playwrights, Actors, and Directors', 45, 55, 2000);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('How to Buy, Sell & Profit on eBay: Kick-Start Your Home-Based Business in Just Thirty Days', 46, 10, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('eBay for Dummies', 47, 54, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('eBay PowerSeller Secrets: Insider Tips from eBay''s Most Successful Sellers', 48, 56, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('What to Sell on ebay and Where to Get It: The Definitive Guide to Product Sourcing for eBay and Beyond', 49, 57, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Starting an eBay Business for Dummies', 47, 54, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('eBay: Top 100 Simplified Tips & Tricks', 50, 54, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('ebay Timesaving Techniques for Dummies', 47, 54, 2004);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('eBay Business All-in-One Desk Reference for Dummies', 47, 54, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Ruby Cookbook', 51, 58, 2006);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Ruby Ann''s Down Home Trailer Park Cookbook', 52, 59, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Ruby Ann''s Down Home Trailer Park BBQin'' Cookbook', 52, 59, 2005);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Ruby''s Low-Fat Soul Food Cookbook', 53, 60, 1996);
INSERT INTO libros (titulo, autor_id, editora_id, año_publicacion) VALUES ('Rails Cookbook: Recipes for Rapid Web Development with Ruby', 54, 58, 2007);
