INSERT IGNORE INTO editoras (editora) VALUES ('Scholastic Inc.');
INSERT IGNORE INTO editoras (editora) VALUES ('Scholastic Inc');
INSERT IGNORE INTO editoras (editora) VALUES ('Scholastic');
INSERT IGNORE INTO editoras (editora) VALUES ('Nimble Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Gramercy Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Del Rey Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Crown');
INSERT IGNORE INTO editoras (editora) VALUES ('Wings Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Broadway Books');
INSERT IGNORE INTO editoras (editora) VALUES ('William Morrow Paperbacks');
INSERT IGNORE INTO editoras (editora) VALUES ('Ballantine Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Houghton Mifflin Harcourt');
INSERT IGNORE INTO editoras (editora) VALUES ('Pragmatic Bookshelf');
INSERT IGNORE INTO editoras (editora) VALUES ('Manning Publications');
INSERT IGNORE INTO editoras (editora) VALUES ('Atheneum Books for Young Readers: Richard Jackson Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Teacher Created Resources');
INSERT IGNORE INTO editoras (editora) VALUES ('Delacorte Press');
INSERT IGNORE INTO editoras (editora) VALUES ('Cherry Lane Music Company');
INSERT IGNORE INTO editoras (editora) VALUES ('The New Press');
INSERT IGNORE INTO editoras (editora) VALUES ('Stoneydale Press');
INSERT IGNORE INTO editoras (editora) VALUES ('Changeling Press');
INSERT IGNORE INTO editoras (editora) VALUES ('Viking Juvenile');
INSERT IGNORE INTO editoras (editora) VALUES ('Firebird');
INSERT IGNORE INTO editoras (editora) VALUES ('iUniverse');
INSERT IGNORE INTO editoras (editora) VALUES ('Tor Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Ivy Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Amistad');
INSERT IGNORE INTO editoras (editora) VALUES ('FT Press');
INSERT IGNORE INTO editoras (editora) VALUES ('Archaia');
INSERT IGNORE INTO editoras (editora) VALUES ('Farrar, Straus and Giroux');
INSERT IGNORE INTO editoras (editora) VALUES ('Farrar Straus Giroux');
INSERT IGNORE INTO editoras (editora) VALUES ('Dramatists Play Service');
INSERT IGNORE INTO editoras (editora) VALUES ('Vintage');
INSERT IGNORE INTO editoras (editora) VALUES ('Routledge');
INSERT IGNORE INTO editoras (editora) VALUES ('North Light Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Chosen Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Association for Supervision & Curriculum Development');
INSERT IGNORE INTO editoras (editora) VALUES ('Kingfisher');
INSERT IGNORE INTO editoras (editora) VALUES ('ASCD');
INSERT IGNORE INTO editoras (editora) VALUES ('Leisure Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Sovereign World');
INSERT IGNORE INTO editoras (editora) VALUES ('Workman Publishing Company');
INSERT IGNORE INTO editoras (editora) VALUES ('One Hour Entertainment');
INSERT IGNORE INTO editoras (editora) VALUES ('Serpent''s Tail');
INSERT IGNORE INTO editoras (editora) VALUES ('Silhouette Desire');
INSERT IGNORE INTO editoras (editora) VALUES ('Ace Books');
INSERT IGNORE INTO editoras (editora) VALUES ('iBooks');
INSERT IGNORE INTO editoras (editora) VALUES ('Putnam');
INSERT IGNORE INTO editoras (editora) VALUES ('Tor Science Fiction');
INSERT IGNORE INTO editoras (editora) VALUES ('Touchstone');
INSERT IGNORE INTO editoras (editora) VALUES ('Clarion Books');
INSERT IGNORE INTO editoras (editora) VALUES ('Whitaker House');
INSERT IGNORE INTO editoras (editora) VALUES ('Thomas Nelson');
INSERT IGNORE INTO editoras (editora) VALUES ('Wiley');
INSERT IGNORE INTO editoras (editora) VALUES ('Heinemann Drama');
INSERT IGNORE INTO editoras (editora) VALUES ('McGraw-Hill/Osborne');
INSERT IGNORE INTO editoras (editora) VALUES ('McGraw-Hill');
INSERT IGNORE INTO editoras (editora) VALUES ('O''Reilly Media');
INSERT IGNORE INTO editoras (editora) VALUES ('Citadel');
INSERT IGNORE INTO editoras (editora) VALUES ('McGraw-Hill/Contemporary Books');
